# Generated by Django 5.0.6 on 2024-11-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_direccion_alter_usuario_rol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('mecanico', 'Mecanico'), ('recepcionista', 'Recepcionista')], default='usuario', max_length=50),
        ),
    ]
