# Generated by Django 5.0.6 on 2024-11-17 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cliente_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente', to_field='rut'),
        ),
    ]
