# Generated by Django 5.0.6 on 2024-11-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_producto_cliente_usuario_usuario_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contraseña',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
