# Generated by Django 5.0.6 on 2024-11-18 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cliente_contraseña'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
    ]
