# Generated by Django 5.0.6 on 2024-11-17 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_cliente_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
